# Site settings
title: Arshdeep Singh's Portfolio
description: Arshdeep Singh's Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "http://arshdeepsingh.me"
# User settings
username: Arshdeep Singh
user_description: I am a Computer Science Undergraduate Student at BITS Pilani, Goa Campus. I am interested in Machine Learning, Oper Source Development and Competitive Coding. Check out my projects!
user_title: Software Developer
email: singh.arshdeep1999@gmail.com
twitter_username: arsh__official
github_username:  iamarshsingh

#Google-analytics
google-analytics:
 id: "UA-122887175-1"

exclude: ['package.json', 'src' , 'node_modules'] 
